pyregence/pyregence

src/clj/pyregence/capabilities.clj, src/clj/pyregence/match_drop.clj, src/cljs/pyregence/components/map_controls/match_drop_tool.cljs
Fixes the following bugs:
1. dev and prod match drops were being double counted if the Match Drop ID matched.
2. The right fire-name was not being passed into the Match Drop emails.
3. For Match Drops without a user-provided display name, the Match Drop email would not display the default naming convention (e.g. "Match Drop 12").
=> Fix a few small Match Drop bugs

src/cljs/pyregence/config.cljs
Adds the CANSAC WRF weather model.
Closes PYR1-903
Layers > Weather
Visitor
1. Go to the weather tab and select the CANSAC WRF model.
All layers except for 1 hour precipitation, smoke, and total cloud cover should load for the CANSAC WRF model. Point info should also work for the model.
---
=> PYR1-903 Add CANSAC WRF weather model

src/cljs/pyregence/pages/login.cljs, src/cljs/pyregence/pages/near_term_forecast.cljs, src/cljs/pyregence/pages/register.cljs, src/cljs/pyregence/pages/reset_password.cljs
Fixes a bug where the active fires markers wouldn't always show up the first time you loaded the site.
Closes PYR1-900
Layers > Active Fires markers
Visitor
- Visit Pyrecast normally
- Do a hard refresh on Pyrecast (Command + Shift + R)
- Open Pyrecast in an incognito window
- Switch between the Active Fires and other tabs on Pyrecast
The active fires markers should always show up whenever you first hit the Active Fires tab (and thus have "*All Active Fires" selected).
=> PYR1-900 Fix a bug with the active fires markers

src/clj/pyregence/cameras.clj, src/cljs/pyregence/components/map_controls/camera_tool.cljs
Adds a link to the live camera feed for both ALERT Wildfire and ALERTCalifornia cameras. You can visit this link by clicking on the logo in the top left corner of a camera (or by clicking the link for a camera that hasn't been refreshed for at least four hours).
Closes PYR1-910
Toolbars > Cameras
Visitor
1. Click on the camera tool
2. For both a camera within California and a camera outside of California, click on the image/logo in the top left of the camera's image. This should either be an ALERTCalifornia or an ALERT Wildfire logo respectively.
You should be taken to (in a new tab) a live feed of the corresponding camera on either the ALERTCalifornia or ALERT Wildfire website.
=> PYR1-910 Link to live feed when clicking on logo

src/clj/pyregence/capabilities.clj, src/clj/pyregence/match_drop.clj, src/cljs/pyregence/components/map_controls/camera_tool.cljs
> Attention: Starting September 14th, alertca.live will redirect to ops.alertcalifornia.org. Please transition over to ops.alertcalifornia.org to ensure uninterrupted site access.
This PR updates the URL in the necessary places and fixes some indentation issues and comments.
=> Update Alert California URL

src/clj/pyregence/cameras.clj
Adds in missing California Alert Wildfire cameras by explicitly not filtering them out in `cameras.clj`.
Closes PYR1-911
Toolbars > Camera Tool
Visitor
1. Click on the camera tool.
2. Navigate around the map, especially near the California side of Lake Tahoe.
There should be Alert Wildfire cameras that appear (they were previously missing). Specifically, there should be 47 new cameras on the map (each camera that was added can be found [here](https://docs.google.com/spreadsheets/d/1BLlLbrltoZmAwnzXq4LRixYj3Ac-rrKQfeHcbnGHDUw/edit?usp=sharing)). An easy camera to check on is the one at Fallen Leaf Lake just south of Lake Tahoe.
=> PYR1-911 Add in missing California Alert Wildfire cameras

src/cljs/pyregence/pages/near_term_forecast.cljs
Adds a custom `nolegend` designation to GeoServer CSS styles which omits any such values from the Pyrecast legend, but still allows for those colors to be displayed on vector line layers. 
Closes PYR1-905
Layers > Transmission Line Vector line layers (fire area, fire volume, impacted structures)
Visitor
1. Navigate to the Risk tab.
2. Select the transmission lines ignition pattern option.
3. Select each of the following output layers: fire area, fire volume, and impacted structures.
4. For each of the above output layers, scroll around the map + zoom in and out.
You should see colors on the layer that don't necessarily correspond exactly with the colors in the legend. i.e. there should be intermediate colors on the map that fall in between the different buckets laid out in the legend.
=> PYR1-905 Add improved vector line styling to Pyrecast

src/cljs/pyregence/config.cljs
Changes the name of the `apcp` layers to fix a bug where the accumulated precipitation layer's point info graph shows the values for the 1-hour precipitation layers instead.
Closes PYR1-901
Point Info > Precipitation Layers
Visitor
1. Navigate to the Weather tab.
2. For each model, click on both the accumulated precipitation and 1-hour precipitation layers.
3. Use the point info tool on a spot where there's some precipitation.
You should see a point info graph that matches the values you're seeing on the screen for each layer.
=> PYR1-901 Precipitation point info bug

.github/PULL_REQUEST_TEMPLATE.md, config.default.edn, src/clj/pyregence/authentication.clj, src/clj/pyregence/views.clj, src/cljs/pyregence/client.cljs, src/cljs/pyregence/components/forecast_tabs.cljs, src/cljs/pyregence/components/nav_bar.cljs, src/cljs/pyregence/config.cljs, src/cljs/pyregence/pages/admin.cljs, src/cljs/pyregence/state.cljs, src/sql/changes/2023-10-31_allowed-orgs.sql, src/sql/functions/user_functions.sql, src/sql/tables/user_tables.sql
Adds a new `org_unique_id` column to the `organizations` table in order to more ergonomically be able to select entire organizations. 
Adds a changefile to add `org_unique_id` values to all existing organizations on production.
Add a new `:psps` key to `config.edn` to keep track of the organizations that are allowed to view the PSPS tab.
Cleans up some of the variable naming surrounding organizations in the codebase.
Closes PYR1-23 PYR1-707
=> PYR1-23 Overhaul the way that the PSPS tab is shown on an organization by organization basis

config.default.edn, src/clj/pyregence/views.clj, src/cljs/pyregence/client.cljs, src/cljs/pyregence/config.cljs, src/cljs/pyregence/state.cljs
Fixes a bug with storing the `allowed-psps-orgs` in `config.edn` and instead places them inline in `config.cljs`.
=> Fix a bug with the PSPS tab always showing

src/clj/pyregence/capabilities.clj, src/cljs/pyregence/components/map_controls/collapsible_panel.cljs
Update the backend to take account for the new format in which PSPS layers are being pushed to `/srv/gis` on `curlew` (e.g. `/srv/gis/psps_zonal/nve/forecast-start-time/layer-name.shp`).
Also cleans up the way in which isochrones are processed on the backend and adds comments to `capabilities.clj`.
=> PYR1-947 Update PSPS routes in Pyrecast

src/clj/pyregence/authentication.clj, src/clj/pyregence/remote_api.clj, src/cljs/pyregence/components/forecast_tabs.cljs, src/cljs/pyregence/config.cljs, src/cljs/pyregence/pages/near_term_forecast.cljs, src/sql/changes/2023-11-16_psps-updates.sql, src/sql/functions/user_functions.sql, src/sql/tables/user_tables.sql
Allow for multiple orgs  to use the PSPS tab. The new `psps_org` column in the `users` table tells us which PSPS data the logged in user should see when they navigate to the PSPS tab. Note that users can only see PSPS layers from one utility company at a time.
Closes PYR1-949
=> PYR1-949 Allow for multiple orgs to see PSPS tab

src/clj/pyregence/authentication.clj, src/sql/changes/2023-12-15_geoserver-logins.sql, src/sql/functions/user_functions.sql, src/sql/tables/user_tables.sql
Adds a `geoserver_credentials` column to the `organizations` table.
Closes PYR1-963
=> PYR1-963 Add GeoServer credentials to organizations

config.default.edn, src/clj/pyregence/authentication.clj, src/clj/pyregence/capabilities.clj, src/clj/pyregence/remote_api.clj, src/cljs/pyregence/components/forecast_tabs.cljs, src/cljs/pyregence/components/login_menu.cljs, src/cljs/pyregence/config.cljs, src/cljs/pyregence/pages/near_term_forecast.cljs, src/cljs/pyregence/state.cljs, src/sql/changes/2023-12-15_geoserver-logins.sql, src/sql/functions/user_functions.sql, src/sql/tables/user_tables.sql
Uses basic auth to call `set-capabilities!` for PSPS orgs. Dynamically sets the `allowed-orgs` for the PSPS tab based on the PSPS orgs in the database. Adds scaffolding such that a list of the currently signed in user's PSPS is easily accessible (including the relevant GeoServer credentials).
Closes PYR1-962 HER-66
=> HER-66 Extend `set-capabilities` for PSPS

src/clj/pyregence/authentication.clj, src/clj/pyregence/remote_api.clj, src/cljs/pyregence/config.cljs, src/cljs/pyregence/pages/near_term_forecast.cljs, src/sql/changes/2023-12-21_remove-psps-org-column.sql, src/sql/functions/user_functions.sql, src/sql/tables/user_tables.sql
Gets rid of the `psps_org` column in the `users` table in place of adding a utility company dropdown on the PSPS tab that's dynamically created based on the PSPS organization that a user is a part of.
Closes HER-63
=> HER-63 Add a utility company dropdown to the PSPS tab

src/cljs/pyregence/components/mapbox.cljs, src/cljs/pyregence/pages/near_term_forecast.cljs, src/sql/changes/2023-12-21_remove-psps-org-column.sql
Adds basic auth to the `GetLegendGraphic`, `GetFeatureInfo`, and `GetTile` WMS requests for all PSPS (private) layers. Based on the currently selected layer, Pyrecast will now figure out which GeoServer basic auth credentials to use (if applicable). The GeoServer credentials are stored in the Pyrecast DB and are tied to a specific organization that the user is a part of.
Closes HER-68
Layers >  Private PSPS layers
User
All private layers, point info, and legends should now load (once logged into an account that has access to them) without needing to be connected to the VPN.
=> HER-68 Adding basic auth to `GetLegendGraphic`, `GetFeatureInfo`, and `GetTile` WMS requests

src/clj/pyregence/capabilities.clj
Moves the `basic-auth` logic to within `set-capabilities!` instead of `set-all-capabilities!` so that the PSPS GeoSync action hooks work properly.
=> Small fix to set-capabilities

src/clj/pyregence/capabilities.clj, src/cljs/pyregence/components/map_controls/collapsible_panel.cljs, src/cljs/pyregence/components/map_controls/match_drop_tool.cljs, src/cljs/pyregence/pages/near_term_forecast.cljs, src/cljs/pyregence/state.cljs, src/sql/changes/2023-12-29_update-psps-underlays.sql
Fixed a bug where utility company underlays don't load unless you have a layer selected that is associated with that utility company. In order to do so, this PR adds state that tracks the most recently selected optional layer, adds a changefile that updates the optional layers' `:filter-sets`, and updates `capabilities.clj` to mimic this update, 
This PR also cleans up the logic relating to the `get-current-layer-geoserver-credentials` function to make it more legible and fixes a typo on the Match Drop tool.
Closes HER-83
PSPS -> Underlays
User
Toggle on and off the PSPS underlays from various tabs.
The underlays (and other layers) should all load normally.
=> HER-83 Fix a few bugs related to the PSPS underlays

src/clj/pyregence/capabilities.clj, src/clj/pyregence/jobs.clj
Adds a timeout clause to `GetCapabilities` calls and allows for the web server to be started without waiting on `set-all-capabilities!` to finish.
Closes HER-443
=> HER-443 Fix some edge cases with Pyrecast deployments

bb.edn, src/cljs/pyregence/pages/near_term_forecast.cljs
Fixes the following two edge cases with private layers on Pyrecast:
1. Log in to Pyrecast as an account with PSPS access
2. Go to the weather tab
3. Turn on a utility company specific transmission lines
4. Try to use the point info tool on the weather tab
5. You get a "no point info available" error from the front-end
6. An example request here would be: `https://shasta.pyregence.org/geoserver/wms?SERVICE=WMS&EXCEPTIONS=application/json&VERSION=1.3.0&REQUEST=GetFeatureInfo&INFO_FORMAT=application/json&LAYERS=fire-weather-forecast_hybrid_20240904_12:tmpf&QUERY_LAYERS=fire-weather-forecast_hybrid_20240904_12:tmpf&FEATURE_COUNT=50000&TILED=true&I=0&J=0&WIDTH=1&HEIGHT=1&CRS=EPSG:3857&STYLES=&BBOX=-12913575.405096125,4226460.030664251,-12908599.603543425,4231435.832216952`
Note that when I …
=> PYR1-988 Fix various private layer edge cases

src/sql/dev_data/dev_data.sql
This is necessary because the org_unique_id column is marked with the sql constraint 'NOT NULL', so without these column values, the SQL inserts will fail.
To reproduce this failure, check out git commit 3bf1b49 and, from the command line, run the dev setup command:  `clojure -M:build-db build-all --dev-data`. This will result in the following psql error: 
```
psql:src/sql/dev_data/dev_data.sql:11: ERROR:  null value in column "org_unique_id" of relation "organizations" violates not-null constraint
DETAIL:  Failing row contains (1, Development, null, null, @pyr.dev, t, t, f, 2024-12-04, null).
```
If you checkout the git commit with the fix (this branch), and re-run the dev setup command above, you will notice this error goes away. This is the desired behavior because we want that column, …
=> Add missing PostgreSQL  values for the column org_unique_id in the table organizations to fix the development setup. 

src/cljs/pyregence/components/map_controls/measure_tool.cljs
Given that most distances calculated are over a thousand meters, it's easier to read in kilometers than in meters. However, our users don't use meters regularly because they are from the U.S., so we should prefer showing the user's miles over kilometers. 
Closes PYR1-970
- [ i think so? Hard to say] Code passes linter rules (`clj-kondo --lint src`)
- [ runs just fine] Feature(s) work when compiled (`clojure -M:compile-cljs`)
- [not sure how to tell if there are new ones, i doubt it ] No new reflection warnings (`clojure -M:check-reflection`)
- [ no need] For any large features/rearchitecting of the codebase, the relevant `docs` were updated (e.g. updating `docs/pyrecast-database.md` when adding a new DB table)
I'm not sure what module was impacted.
I assume all roles can see this chnage …
=> PYR1-970 add miles and kilometers to measure distance tool modal

src/cljs/pyregence/config.cljs, src/cljs/pyregence/pages/near_term_forecast.cljs
This change disables auto-zooming when on the Risk or PSPS tab. If a Utility Company wants to re-enable auto-zooming for a given Risk Ignition Pattern, we can do that by updating the database like so:
```
UPDATE public.organization_layers
SET layer_config='{:auto-zoom? true <TODO rest of config ommited>}'
WHERE org_layer_uid=<TODO>;
```
Note some` < values >` have been omitted.
=> PYR1-1016 logged in users map should stay where they are when switching between tabs

src/cljs/pyregence/pages/near_term_forecast.cljs
=> PYR1-991 (bugfix) the :default-option value needs to be a keyword to match whats

bb.edn, src/cljs/pyregence/geo_utils.cljs
bugfix
Closes PYR1-971
Measurement Tool
User
1. Go to google maps and measure some distance
2. Go to pyrecast and do the same measurement
Compare the results: should be similar.
=> PYR1-971 measure distance tool does not accurately capture north south direction

src/cljs/pyregence/components/forecast_tabs.cljs, src/cljs/pyregence/pages/near_term_forecast.cljs, src/cljs/pyregence/state.cljs
Toast "No active fires." when there are no active fires and it's the first time the active fire tab has been visited.
=> PYR1-975 add toast message when there are no active fires

src/cljs/pyregence/config.cljs, src/cljs/pyregence/pages/near_term_forecast.cljs
Fire and risk forecasts are now always displayed in UTC.
Closes PYR1-1026
=> PYR1-1026 fire and risk forecast now always display in utc.

README.org, src/cljs/pyregence/components/map_controls/collapsible_panel.cljs, src/cljs/pyregence/config.cljs
Updates the text for the fire perimeters underlay from 2024 to 2025 (now that the underlying layer has been updated). Also updates the README.
Closes PYR1-1033
Confirm that the text in the optional layers panel (as well as the help text/tooltip) says "2025 fire perimeters" and not "2024 fire perimeters".
=> PYR1-1033 Update 2024 fire perimeters to 2025

src/cljs/pyregence/config.cljs
We want to add other Mapbox base maps to PyreCast
Closes PYR1-1035
Change the basemap types in the bottom left menu.
Observe the layer changing.
Add more layers like transmission lines, structures etc. (from the "Otional Layers" menu)
Do some exploration testing changing basemap types, like zooming in/out etc.
All
Should change the baselayer normally
=> PYR1-1035 Introduce other mapbox layer options in base-map-options

src/cljs/pyregence/components/mapbox.cljs, src/cljs/pyregence/pages/near_term_forecast.cljs
Selecting the forecast should be done after the mapbox loads because Mapbox asynchronously fetches styles, and likely does other work asynchronously in it's constructor, which means the app needs a way to do work after that async work finishes.
That work cannot be done before, as doing it before will cause issues like the active fire icons not loading, which is really more like a symptom of the whole mapbox program failing.
To facility doing the work explicitly after the mapbox loads, we take advantage of the Mapbox's lifecycle load event. Here is the link:
https://docs.mapbox.com/mapbox-gl-js/api/map/#map.event:load
and here is an example from that link:
```
// Initialize the map
const map = new mapboxgl.Map({});
// Set an event listener that fires
// when the map has finished loading. …
```
=> PYR1-1030 Select the forecast after the mapbox loads.

src/cljs/pyregence/pages/near_term_forecast.cljs
The fix to PYR1-975 wasn't quite working as expected because of an extra check in the `cond` statement altered in this PR. This is because the `no-param-layers?` check was never being hit due to the fact that the active fires icon layer exists even when it doesn't hold any data:
```clojure
cljs.user=> @pyregence.state/param-layers
[{:hour 0, :workspace "fire-detections_active-fires", :layer-group "", :forecast "fire-detections", :times ni
l, :type "active-fires", :model-init "20250127_111200", :layer "fire-detections_active-fires:active-fires_202
50127_111200", :extent ["0.0" "0.0" "-1.0" "-1.0"], :filter-set #{"20250127_111200" "fire-detections" "active
-fires"}}]
```
Simply removing that check restores the functionality that we expect. When there are no active fire forecasts (as per the …
=> PYR1-975 Small bug fix with no active fires toast message

src/cljs/pyregence/pages/near_term_forecast.cljs
This change makes it so the browser app shows the active fire forecasts when there are some; otherwise, it sends the user to the weather forecast tab. This behavior happens on the first load.
Closes PYR1-1048
It affects which forecast tab shows on the first load. 
ALL
Run the local dev setup and hardcode the active-fire-count (line 621 in near_term_forecast.cljs) to zero. Then do a hard refresh and notice that it will take you to the weather page. Now hardcode the active-fire-count to 1 and do a hard refresh, it will go to the active fire tab as desired.
=> PYR1-1048 show active fires forecast when there are some, otherwise show the weather tab.

src/clj/pyregence/match_drop.clj
Updates the fuel version and the WorldGen server path in `match_drop.clj` to restore functionality to the Match Drop tool. 
Closes PYR1-1037
The Match Drop tool should show the available weather dates when first clicked on.
=> PYR1-1037 Fix Match Drop by updating fuel version and WorldGen server path

package-lock.json, package.json, src/cljs/pyregence/components/common.cljs, src/cljs/pyregence/components/map_controls/information_tool.cljs, src/cljs/pyregence/components/resizable_window.cljs, src/cljs/pyregence/components/vega.cljs, src/cljs/pyregence/pages/near_term_forecast.cljs
Remove deprecated code
```clojure
(rd/dom-node this)
```
And replace with
```clojure
(.-current ref) ;; (let [ref (react/createRef)])
```
Issue: When upgrading to reagent 1.2.0 we’ve started to get deprecation notes when compiling or working with fighweel: reagent.dom/dom-node is deprecated
Fix: re-write code in such a way that fixes the warning.
Reference: re-com [issue](https://github.com/day8/re-com/issues/329)
re-com commit that fixes it: [Merge RolT PR: Removed deprecated usage of react dom node](https://github.com/day8/re-com/commit/e8a9d14)
Closes PYR1-1011
All
All
1. Configure the app to run in dev mode (call `bb dev`)
2. Test the app thoroughly. Everything should work as before.
3. Configure the app to run in prod mode (call `bb prod`)
4. Test the app thoroughly. Everything …
=> PYR1-1011 fix "dom-node" warnings

src/cljs/pyregence/pages/near_term_forecast.cljs
Before there is a scroll bar we didn't want:
Now there isn't!
Closes PYR1-1066
=> PYR1-1066 hide scrollbar

src/clj/pyregence/capabilities.clj, src/cljs/pyregence/config.cljs
and have them display on top of the other layers.
Part of PYR1-1010
ALL
Click on U.S State and county boundaries optional layers and have them display. Note that this change alone wont do that.
=> PYR1-1010 Add U.S State and county boundaries optional layers

.dir-locals.el
By using `cider-clojure-cli-aliases` which isn't deprecated & picking
the build tool so that the user doesn't have to.
=> Improve dir locals

src/cljs/pyregence/components/common.cljs, src/cljs/pyregence/components/login_menu.cljs
This commit has two small changes to the tooltips: 
first the admin tooltip is properly displaying under it:
Before:
After:
Secondly, the all the tooltips are more aligned:
Before:
After:
=> PYR1-1074 Now the tooltip for admin correctly displays under the admin pic

bb.edn
We add an option to start the cljs compilation/figwheel server in dev mode without having to start the repl for folks who don't want repl or experiencing weird timeout errors when repl is on (like me). 
Closes PYR1-1080
=> PYR1-1080  Add dev-norepl to bb to start without repl as an option

src/cljs/pyregence/config.cljs
Add new source fuel layers
Closes PYR1-1034
Original files can also be downloaded from the jira ticket (https://sig-gis.atlassian.net/browse/PYR1-1034?focusedCommentId=17573) but are the below:
- [ca-2022](https://www.dropbox.com/scl/fi/vh699cvp7841h33oo9mcm/CAL2022_FireSeasonFuelscape_20220502.zip?rlkey=7bvicerizwfnlk8zbd499sw6b&e=2&st=ghidexyr&dl=0)
- [ca-2021](https://www.dropbox.com/scl/fi/2ljk7irmaqjiyxxyom6lz/CAL2021_FireSeasonFuelscape_20210527.zip?rlkey=7ldk1ahjo0bsw07fe89asatqw&st=7x1mdjbc&dl=0)
After downloading them, I've kept only the .tif ones and renamed them to asp.tif, cbd.tif etc.
See https://sig-gis.atlassian.net/browse/PYR1-1034?focusedCommentId=17573 
transcprition:
> Since the original files were not recognized by the geoserver, I had to "manually" change the files in …
=> PYR1-1034 add :ca-fuelscapes-2021

src/clj/pyregence/red_flag.clj
The NWS hazards API endpoint changed, breaking the red flag warnings layer on Pyrecast. This PR updates the endpoint. I found the new endpoint by going to https://www.weather.gov/wrh/hazards and scrolling through the network tab until I found the request they were making to pull in the red flags layer.
Closes PYR1-1081
Make sure the red flag warnings layer works.
=> PYR1-1081 Fixing the red flag layer

src/cljs/pyregence/pages/login.cljs, src/cljs/pyregence/pages/register.cljs
This PR must be merged only after https://github.com/pyregence/pyregence/pull/928 (mainly for the purpose of showing a sample gtag-id in the [config.edn](https://github.com/pyregence/pyregence/pull/928/files#diff-2269e6f261ddc8af81995b116b45d24d83919a208aefbb51339a4b1f460c8658R72) file)
Start tracking:
- User is successfully registered (as indicated on the successful registration API)
- User is successfully logged in
Closes PYR1-1073
Login/registration
All
1. To really test you could create a google analytics account for yourself
2. Then configure it and get a G-* tag
3. Then start pyrecast with your G-* tag in the config.edn file (:triangulum.views/gtag-id entry)
4. Then register a new user successfully
5. And check the event in google analytics at Reports -> Realtime Overview -> "Event …
=> PYR1-1073 add user conversion events to ga4 in pyrecast

src/cljs/pyregence/analytics.cljs, src/cljs/pyregence/components/map_controls/tool_bar.cljs, src/cljs/pyregence/components/map_controls/zoom_bar.cljs, src/cljs/pyregence/pages/login.cljs, src/cljs/pyregence/pages/near_term_forecast.cljs, src/cljs/pyregence/pages/register.cljs
Same as https://github.com/pyregence/pyregence/pull/930 and #928 but for all the right sided tools, namely:
1. Point information
2. Cameras
3. Red flags
4. Historical fires
5. Measure distance
6. Legend
7. Share
8. 3D terrain
9. Center on my location
10. Zoom to fit later
11. Zoom in plus
12. Zoom out minus
Closes PYR1-1076
All
All
1. Access pyrecast, click a right sided tool
2. Check google analytics to check the triggered event
See how to do `2` #928 and #930 Testing sections
See there is a `tool-usage`:
Then the `tool-clicked`:
And the concrete events:
=> PYR1-1076 add pyrecast tool usage ga4 events

config.default.edn, src/clj/pyregence/handlers.clj, src/cljs/pyregence/client.cljs, src/cljs/pyregence/pages/near_term_forecast.cljs, src/cljs/pyregence/state.cljs
Use show-disclaimer instead of dev-mode in the config and update the usage in the cljs state code. 
Closes PYR1-1069
=> PYR1-1069  Rename `dev-mode` `config.edn` key to `show-disclaimer` across Pyrecast

src/cljs/pyregence/components/map_controls/collapsible_panel.cljs
Hide Isochrones layer if it's dependent-type has changed.
Closes PYR1-908
0. Checkout git commit 253befd81e6200fc3a418042ec944816f3a6b686
1. Go to [PyreCast.org|http://PyreCast.org] and select Active Fires from the tab options
2. Select an active fire from the Fire Name dropdown (I suggest AZ Pim Bryce as some others are missing)
3. Check the Modeled perimeter box from the Optional Layers panel
4. Select a different option from the Output dropdown
5. The Modeled perimeter that appeared in step 3 will disappear
6. Uncheck the Modeled perimeter box
7. Recheck the Modeled perimeter box and the layer should reappear
Now, check out the latest on this branch, repeat steps 1-7, and see that in step 5, it never disappears, which is the desired behavior.
=> PYR1-908/Hide Isochrones layer if it's dependent-type has changed

src/clj/pyregence/capabilities.clj
`set-all-capabilities!` is called with one argument (the unused `session`). This PR updates a call to `set-all-capabilities!` that was passing in 0 arguments.
=> Fixing a call to set-all-capabilities

src/cljs/pyregence/config.cljs
Similar to #926, but for `landfire-2-5-0` fuels.  
Closes PYR1-1146
Fuel layers
All
1. Click `fuels` tab
2. Select "LANDFIRE 2.5.0 (2025 capable)" Source
3. Check the layer works on the map
4. Select other `Layer`, like "Canopy Cover (%)" for example
5. Do step `3.`
New layer works
See #926, should be similar.
Files are in `shasta` already:
```bash
dsilva@shasta:~$ ls /srv/gis/fuels_and_topography/landfire-2.5.0 -ltrh
total 3.3G
-rwxr-xr-x 1 sig-app domain users 483M Jul  6 20:12 cbd.tif
-rwxr-xr-x 1 sig-app domain users 582M Jul  6 20:12 cbh.tif
-rwxr-xr-x 1 sig-app domain users 426M Jul  6 20:12 cc.tif
-rwxr-xr-x 1 sig-app domain users 453M Jul  6 20:12 ch.tif
-rwxr-xr-x 1 sig-app domain users 583M Jul  6 20:12 fbfm13.tif
-rwxr-xr-x 1 sig-app domain users 823M Jul  6 20:12 fbfm40.tif …
```
=> PYR1-1146 Add `landfire-2.5.0` fuels

src/clj/pyregence/capabilities.clj
Updated remove-workspace to handle workspace-name regexes.
PYR1-1149
=> PYR1-1149: BUG: Fix `remove-workspace` function such that it processes regex strings properly

src/cljs/pyregence/components/common.cljs, src/cljs/pyregence/components/map_controls/camera_tool.cljs, src/cljs/pyregence/components/map_controls/weather_station_observation_latest_tool.cljs
This branch's purpose is to fix the alignment of the camera and weather station tips to their tools.
Closes PYR1-1184
For each tool: weather-station and camera, hover over binoculars (zoom-in) and expect to see the tip closely aligned just under the tip, now click the tool and do the same for the zoom-out icon. Also, check the other tool tips and notice how they haven't changed!
=> PRY1-1184 fix alignment of tip to tool for camera and WS.
